# Recommended Plugins

[PlaceholderAPI]
description = "The official placeholder api for Allay."
authors = ["daoge_cmd"]
github = "https://github.com/AllayMC/PlaceholderAPI"

[EconomyAPI]
description = "EconomyAPI is a plugin that unifies all economy plugins under one single API."
authors = ["daoge_cmd"]
github = "https://github.com/AllayMC/EconomyAPI"

[LuckPerms]
description = "A permission plugin for Minecraft servers."
authors = ["Luck", "daoge_cmd"]
github = "https://github.com/AllayMC/LuckPerms"

[LuckPermsPlaceholders]
description = "Optional plugin which provides LuckPerms placeholders for Allay's PlaceholderAPI."
authors = ["Luck", "daoge_cmd"]
github = "https://github.com/AllayMC/LuckPermsPlaceholders"

[Spark]
description = "A performance profiler for Minecraft clients, servers, and proxies."
authors = ["Luck", "IWareQ", "daoge_cmd"]
github = "https://github.com/AllayMC/spark-extra-platforms"

[Terra]
description = "Voxel world generation modding platform."
authors = ["daoge_cmd", "IWareQ", "dfsek", "duplexsystem", "Astrash", "solonovamax", "Sancires", "Aureus", "RogueShade"]
github = "https://github.com/PolyhedralDev/Terra"

[TemplateWorld]
description = "TemplateWorld is a plugin to make it able to create a runtime-only world based on a 'template world'."
authors = ["daoge_cmd"]
github = "https://github.com/AllayMC/TemplateWorld"

# Other Plugins

[Aitokoto]
description = "An AllayMC plugin that send a random quote from Hitokoto to the newly joined player."
authors = ["daoge_cmd"]
github = "https://github.com/smartcmd/Aitokoto"

[Amoji]
description = "An emoji plugin for AllayMC server that displays emoji particle effects above players' heads!"
authors = ["daoge_cmd"]
github = "https://github.com/smartcmd/Amoji"

[Aether]
description = "Aether is a blazing-fast, low-latency TCP bridge connecting WaterdogPE Proxy (Master) with multiple AllayMC Servers (Nodes)."
authors = ["Miroshka"]
github = "https://github.com/Miroshka000/Aether"

[Holograms]
description = "Holograms is a feature-rich hologram plugin for Allay servers."
authors = ["Miroshka"]
github = "https://github.com/Miroshka000/HologramsAllay"

[AllayMap]
description = "A minimalistic and lightweight world map viewer for Allay servers, using the vanilla map rendering style."
authors = ["daoge_cmd"]
github = "https://github.com/smartcmd/AllayMap"

[NoSpaceInName]
description = "NoSpaceInName automatically detects spaces in player names upon login and replaces them with a configured character."
authors = ["Miroshka"]
github = "https://github.com/Miroshka000/NoSpaceInName"

[KDR]
description = "Simple and Efficient Kill/Death Ratio Statistics for Allay."
authors = ["Miroshka"]
github = "https://github.com/Miroshka000/KDR"

[Aegis]
description = "Advanced Region Management System for Allay."
authors = ["Miroshka"]
github = "https://github.com/Miroshka000/Aegis"

[Aconomy]
description = "Aconomy is an simple implementation of AllayMC's official EconomyAPI."
authors = ["daoge_cmd"]
github = "https://github.com/smartcmd/Aconomy"

[Sidebar]
description = "Sidebar plugin for Allay server."
authors = ["daoge_cmd"]
github = "https://github.com/smartcmd/Sidebar"

[Aenu]
description = "A powerful, configurable menu plugin for AllayMC servers with full PlaceholderAPI support."
authors = ["daoge_cmd"]
github = "https://github.com/smartcmd/Aenu"

[BlackBE]
description = "BlackBE integration for Allay server."
authors = ["daoge_cmd"]
github = "https://github.com/smartcmd/BlackBE"

[Essentials]
description = "Essential plugin for Allay server."
authors = ["daoge_cmd"]
github = "https://github.com/smartcmd/Essentials"

[Imager]
description = "Show image in your Allay server!"
authors = ["daoge_cmd"]
github = "https://github.com/smartcmd/Imager"

[NBSAllay]
description = "Note block song player for Allay server."
authors = ["daoge_cmd"]
github = "https://github.com/smartcmd/NBSAllay"

[ChatFormatter]
description = "A simple chat formatter plugin for Allay."
authors = ["daoge_cmd"]
github = "https://github.com/smartcmd/ChatFormatter"

[HuHoBot]
description = "HuHoBot for AllayMC, enabling the official QQ bot to connect to your server."
authors = ["HuoHuas001", "daoge_cmd"]
github = "https://github.com/HuHoBot/KotlinMergeAdapter"

[ServerInfo]
description = "Show some information through scoreboard & bossbar."
authors = ["daoge_cmd"]
github = "https://github.com/AllayMC/ServerInfo"

[RemoteCommand]
description = "Execute server command through http interface."
authors = ["daoge_cmd"]
github = "https://github.com/AllayMC/RemoteCommand"

[AllayScalaLibrary]
description = "Scala standard library and scala toolkit packages for allay."
authors = ["scala"]
github = "https://github.com/ScAllay/AllayScalaLibrary"

[DiscordRelay]
description = "A Simple Minecraft to Discord Relay for the AllayMC Server Software!"
authors = ["Acktar"]
github = "https://github.com/acktarbadulla/DiscordRelay-AllayMC"

[SimpleScoreboard]
description = "A lightweight and customizable scoreboard plugin for AllayMC."
authors = ["Acktar"]
github = "https://github.com/Mythical-Games/SimpleScoreboard"

[allaymc-kotlinx]
description = "Kotlin-style Extension Library and Shared Standard Library for Allay Server"
authors = ["MineBuilder"]
github = "https://github.com/MineBuilders/allaymc-kotlinx"

[allaymc-nodejs-runtime]
description = "A Node.js runtime for Allay!"
authors = ["MineBuilder"]
github = "https://github.com/MineBuilders/allaymc-nodejs-runtime"

[allaymc-kts-host]
description = "Load Kotlin Script in Allay!"
authors = ["MineBuilder"]
github = "https://github.com/MineBuilders/allaymc-kts-host"
